### ISSUE TITLE
Navigation around AIMS lab

### ISSUE THREAD

**Issue by wafeeqaj** [osu-aims-capstone/smart-cart#30]
- [ ] Camera publishing data
- [x] Use 2D map to take predefined location input
- [x] Use RPM for calculating distance travelled
- [ ] Use computer vision to verify the cart has reached destination

**Comment by laurendudgeon** [comment]
The camera was not implemented, we are using ultrasonic sensors to avoid collisions and RPM to calculate the distance traveled, then comparing the distance to the predefined map.
